/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.ziloka.ProxyBroker;

import com.ziloka.ProxyBroker.cmds.FindCommand;
import org.junit.Assert;
import org.junit.FixMethodOrder;
import org.junit.Test;
import junit.framework.TestCase;
import org.junit.runners.MethodSorters;
import picocli.CommandLine;

import java.io.PrintWriter;
import java.io.StringWriter;

// https://picocli.info/#_testing_your_application
@FixMethodOrder(MethodSorters.NAME_ASCENDING)
public class FindCommandTest {

    @Test
    public void findCommandShouldWork(){
        ProxyBroker proxyBroker = new ProxyBroker();
        CommandLine cmd = new CommandLine(proxyBroker);
        StringWriter sw = new StringWriter();
        cmd.setOut(new PrintWriter(sw));

        // black box testing
        int exitCode = cmd.execute("find", "--types", "http");
        Assert.assertEquals(0, exitCode);
        // white box testing

    }

}
